python3 train_edslstm.py --config_json_file=EDSLSTM_TPU_001.json --execution=0
python3 train_edslstm.py --config_json_file=EDSLSTM_TPU_001.json --execution=1
python3 train_edslstm.py --config_json_file=EDSLSTM_TPU_001.json --execution=2
python3 train_edslstm.py --config_json_file=EDSLSTM_TPU_001.json --execution=3
python3 train_edslstm.py --config_json_file=EDSLSTM_TPU_001.json --execution=4
python3 train_edslstm.py --config_json_file=EDSLSTM_TPU_001.json --execution=5
python3 train_edslstm.py --config_json_file=EDSLSTM_TPU_001.json --execution=6
python3 train_edslstm.py --config_json_file=EDSLSTM_TPU_001.json --execution=7
python3 train_edslstm.py --config_json_file=EDSLSTM_TPU_001.json --execution=8
python3 train_edslstm.py --config_json_file=EDSLSTM_TPU_001.json --execution=9
